version: '3.8'

services:
  homepage:
    build: .
    container_name: CMD_HOMEPAGE
    ports:
      - "8893:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./assets:/usr/share/nginx/html/assets
